package dwo.gameserver.model.actor.restriction;

/**
 * @author Yorie
 */
public enum RejectionReason
{
	PASSED,
	PARTICIPATING_OLYMPIAD,
	PARTICIPATING_INSTANCE,
	OBSERVING,
	RESTRICTED_ZONE,
	DEAD,
	PARTICIPATING_COMBAT,
	COMBAT_FLAG_EQUIPPED,
	TRADING,
	PARTICIPATING_SIEGE,
	BAD_REPUTATION,
	CASTING_SPELL,
	ATTACKING,
	PRISONER,
	FLYING,
	PARTICIPATING_DUEL
}
