package dwo.gameserver.model.actor.restriction;

/**
 * @author Yorie
 */
public enum RestrictionCheck
{
	SUCCESS,
	ONLINE,
	PARTICIPATING_OLYMPIAD,
	PRISONER,
	CASTING,
	CASTING_SIMULTANEOUSLY, // TODO: Impl
	ATTACKING,
	DEAD,
	PARTICIPATING_SIEGE,
	PARTICIPATING_DUEL,
	COMBAT_FLAG_EQUPPIED,
	PARTICIPATING_COMBAT,
	BAD_REPUTATION,
	OBSERVING,
	FLYING,
	PARTICIPATING_INSTANCE,
	CAN_SUMMON_TO_INSTANCE,
	IN_NO_SUMMON_FRIEND_ZONE,
	IN_BOSS_ZONE,
	TRADING,
	CAN_MOVE,
	CAN_CAST,
	MARRIED,
	PARTICIPATING_EVENT,
	PARTICIPATING_SAME_INSTANCE,
	IMMOBILIZED
}