package dwo.gameserver.model.items.base.proptypes;

/**
 * L2GOD Team
 * User: ANZO
 * Date: 23.02.12
 * Time: 8:58
 */

public enum MaterialType
{
	MATERIAL_STEEL,
	MATERIAL_FINE_STEEL,
	MATERIAL_BLOOD_STEEL,
	MATERIAL_BRONZE,
	MATERIAL_SILVER,
	MATERIAL_GOLD,
	MATERIAL_MITHRIL,
	MATERIAL_ORIHARUKON,
	MATERIAL_PAPER,
	MATERIAL_WOOD,
	MATERIAL_CLOTH,
	MATERIAL_LEATHER,
	MATERIAL_BONE,
	MATERIAL_HORN,
	MATERIAL_DAMASCUS,
	MATERIAL_ADAMANTAITE,
	MATERIAL_CHRYSOLITE,
	MATERIAL_CRYSTAL,
	MATERIAL_LIQUID,
	MATERIAL_SCALE_OF_DRAGON,
	MATERIAL_DYESTUFF,
	MATERIAL_COBWEB,
	MATERIAL_SEED,
	MATERIAL_FISH,
	MATERIAL_RUNE_XP,
	MATERIAL_RUNE_SP,
	MATERIAL_RUNE_PENALTY
}
