package dwo.gameserver.model.player;

/**
 * L2GOD Team
 * User: ANZO
 * Date: 17.08.12
 * Time: 3:12
 */

public enum FloodAction
{
	BBS_BUFF_SAVE,
	BBS_BUFF_LOAD,
	BBS_BUFF_HEAL,
	BBS_BUFF_CANCEL,
	ITEM_AUCTION_SHOW,
	ITEM_AUCTION_BID,
	MAIL_CANCEL,
	MAIL_GET,
	MAIL_SEND,
	COMMISSIN_ADD,
	BUY_ITEM,
	SELL_ITEM,
	DEPOSIT_ITEM,
	DROP_ITEM,
	DESTROY_ITEM,
	ADD_ITEM,
	REFUND_ITEM,
	USE_ITEM,
	TRADE,
	WITHDRAW_ITEM,
	RECIPE_CREATE,
	GET_FTOM_PET_ITEM,
	PET_USE_ITEM,
	HENNA_EQUIP,
	HENNA_REMOVE,
	CHAT_HERO,
	CHAT_GLOBAL,
	CHAT_TRADE,
	ROLLING_DICE,
	SUMMON_ITEMS,
	CLASS_CHANGE,
	CLASS_ADD,
	SKILL_MOUNT,
	CHARACTER_DELETE,
	CHARACTER_RESTORE,
	CHARACTER_SELECT,
	MULTISELL_CHOOSE,
	PING,
	CLAN_BOARD_SEARCH,
	CLAN_BOARD_DRAFT_SEARCH
}